<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>
            Marcatura in TEI per esame di DHDMCH
        </title>
        <author xml:id="AD">
         <persName>Alba d'Elia</persName>
         <idno type="ORCID">0009-0009-3626-6779</idno>
        </author>
      </titleStmt>
      <publicationStmt>
        <p>Pubblicato su GitHub come esercizio di marcatura TEI.</p>
      </publicationStmt>
    </fileDesc>
    <profileDesc>
      <langUsage>
        <language ident="it">Italiano</language>
      </langUsage>
      <textClass>
        <keyword scheme="subject">Cultural Heritage</keyword>
        <keyword scheme="project type">Research</keyword>
      </textClass>
    </profileDesc>
  </teiHeader>
  
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>Le Chiese di Roma</title>
        <author>Diego Angeli</author>
      </titleStmt>
      <publicationStmt>
        <publisher>Società Editrice Dante Alighieri</publisher>
        <date>1903</date>
      </publicationStmt>
      <sourceDesc>
        <p>Testo tratto da documenti storici non strutturati, rielaborato in formato XML secondo le linee guida TEI.</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>

  <text>
    <body>
      <p>
        <head>S. ANASTASIA</head>
        In fondo a <ref type="placeName">via S. Teodoro</ref>, vicino alla <ref type="placeName">piazza dei Cerchi</ref>. La data della fondazione di questa <ref type="place">chiesa</ref> è incerta, ma un documento ci dice che esisteva già sotto <ref type="persName" target="https://www.wikidata.org/wiki/Q162135">Gelasio</ref>, nel <date when="992" type="historical">992</date>, il che farebbe risalire la sua origine al <date when="IX" type="construction"><num type="roman" value="9">IX secolo</num></date>. La tradizione vuole infatti che sia stata edificata da <ref type="persName" target="https://www.wikidata.org/wiki/Q232427">Apollonia</ref>, <ref type="person">matrona romana</ref>, circa l'anno <date when="300" type="construction">300</date>. Era del resto una <ref type="place">chiesa</ref> importante nel Medioevo, tanto che il <ref type= "person">papa</ref> vi celebrava la prima messa il giorno di <ref type="event">Natale</ref> e qui si radunava la <ref xml:lang="la" type="event">collecta</ref> per la stazione a <ref type="person" target="https://www.wikidata.org/wiki/Q262751">S. Sabina</ref>. Nel <date when="769" type="">796</date>, a quanto riferisce <ref type="persName" target="https://www.wikidata.org/wiki/Q125984">Anastasio bibliotecario</ref>, <ref type="persName" target="https://www.wikidata.org/wiki/Q132086">Leone</ref> <ref type="num" value="3">III</ref> restaurò il tetto. Nel <date when="1210" type="renovation">1210</date> <ref type="persName"><num type="roman" value="3">III</num></ref> vi fece nuovi restauri e l'arricchì di decorazioni interne, fra cui <num type="ordinal" value="2">due</num> amboni che andarono distrutti più tardi. Nel <date when="1475" type="renovation">1475</date> <ref type="persName" target="https://www.wikidata.org/wiki/Q163514">Sisto <num type="roman" value="4">IV</num> (Della Rovere)</ref> la risarcì in quelle parti che minacciavano rovina.</p>
      <p>E così rimase nel suo aspetto primitivo fino al <date when="1636" type="renovation">1636</date>, anno in cui, abbattuta in parte da un <ref type="event">temporale</ref>, fu riedificata per ordine di <ref type="persName" target="https://www.wikidata.org/wiki/Q131579">Urbano <num type="roman" value="8">VIII</num> (Barberini)</ref>. Ne fu <ref type="person">architetto</ref> <ref type="persName" target="https://www.wikidata.org/wiki/Q87128958">Luigi Arrigucci</ref>: ma non è ben certo chi sia l'autore della facciata.</p>
      <p>Perchè sebbene alcuni <ref type="person">storici</ref> l'attribuiscano a quell'<ref type="person">artista</ref>, il <ref type="persName" target="https://www.wikidata.org/wiki/Q110134658">Fraschetti</ref> avrebbe trovato un'antica stampa che ne indicherebbe come <ref type="person">autore</ref> il <ref type="persName" target="https://www.wikidata.org/wiki/Q160538">Bernini</ref>.
      </p>
      <p>Nel <date when="1703" type="renovation">1703</date> il <ref type="person">cardinale <ref type="persName" target="https://www.wikidata.org/wiki/Q3105117">Costaguti</ref></ref> rifaceva la volta della tribuna. Nel <date when="1722" type="renovation">1722</date> il <ref type="person">cardinale <ref type="persName" target="https://www.wikidata.org/wiki/Q3346439"><ref xml:lang="pt" type="name">Nunez de Cunha</ref></ref></ref> portoghese ne riduceva l'interno allo stato attuale. Finalmente <num type="ordinal" value="2">due</num> ultimi restauri furono fatti nel secolo scorso: uno nel <date when="1818" type="renovation">1818</date> da <ref type="persName" target="https://www.wikidata.org/wiki/Q124754">Pio <num type="roman" value="7">VII</num> (Chiaramonti)</ref> e l'altro nel <date when="1850" type="renovation">1850</date> da <ref type="persName" target="https://www.wikidata.org/wiki/Q43720">Pio <num type="roman" value="9">IX</num> (Mastai-Ferretti)</ref>.</p>
      <p>Questa <ref type="place">chiesa</ref> è quasi sempre chiusa, eccettuata la domenica dalle <num type="cardinal">7</num> alle <num type="cardinal">8</num> del mattino. Per visitarla si suoni alla porta a destra della facciata, dove è l'<ref type="place">abitazione</ref> del <ref type="person">custode</ref>.</p>
      <p>Interno. — E' diviso in <num type="cardinal" value="3">tre</num> navi, sorrette da pilastri a cui sono addossate le antiche <num type="cardinal">14</num> colonne che sostenevano la volta. Nel mezzo del soffitto: <title><ref type="event">Martirio</ref> di S. Anastasia</title> di <ref type="persName" target="https://www.wikidata.org/wiki/Q3856437">Michelangelo Cerruti</ref>. A destra: 1. Cappella: <title>S. Giovanni Battista del <ref type="persName" target="https://www.wikidata.org/wiki/Q1192715">Mola</ref></title>. - 2. (In fondo all'abside): <title>I fatti della vita di S. Carlo e di S. Filippo Neri</title> di <ref type="persName" target="https://www.wikidata.org/wiki/Q3220072">Lazzaro Baldi</ref>. - 3. (Nella crocera). Sull'altare: <num type="cardinal" value="2">due</num> colonne di breccia rossa. Quadro a olio rappresentante S. Toribio del <ref type="persName" target="https://www.wikidata.org/wiki/Q963875">Trevisani</ref>. Sepolcro del <ref type="person">cardinale <ref type="persName">Casimiro Hoefflin</ref></ref> (<date when="1827" type="construction">1827</date>). Altar maggiore: architettura di <ref type="persName" target="https://www.wikidata.org/wiki/Q2024585">Onorio Longhi</ref>. <title>La <ref type="event">Natività</ref> di <ref type="persName">Gesù</ref> <characterName>Cristo</characterName></title> di <ref type="persName" target="https://www.wikidata.org/wiki/Q3220072">Lazzaro Baldi</ref>. Sotto l'altare: statua giacente di <title>S. Anastasia</title>, scultura che <ref type="persName" target="https://www.wikidata.org/wiki/Q1348674">Ercole Ferrata</ref> eseguì sopra un bozzetto dell'<title>Aprile</title> di evidente imitazione berniniana. Nella volta: <title>Gloria della Santa</title> anche questa del <ref type="persName" target="https://www.wikidata.org/wiki/Q3220072">Baldi</ref>. Nell'abside: sepolcri dei <ref type="person">cardinali</ref> <ref type="persName" target="https://www.wikidata.org/wiki/Q3750224">Francesco Maria Febei</ref> (<date when="1680" type="construction">1680</date>) a destra; <ref type="persName">Pier Paolo Febei</ref> (<date when="1649" type="construction">1649</date>), a sinistra, coi busti in bronzo, opere tutte di <ref type="persName">Tommaso Pipoli</ref>. A sinistra: 1. Cappella: <title>San Giorgio</title> di <ref type="persName" target="https://www.wikidata.org/wiki/Q3592316">Stefano Parocel</ref> - Sepolcro del <ref type="person">cardinale <ref type="persName" target="https://www.wikidata.org/wiki/Q66201">Carlo Augusto de Reisach</ref></ref>, bavarese (<date when="1870" type="construction">1870</date>) - 2. (Nella crocera) Sull'altare: <num type="cardinal" value="2">due</num> colonne di rarissimo alabastro giallo.</p>
      <p>La <title>Madonna del rosario</title>, quadro di <ref type="persName" target="https://www.wikidata.org/wiki/Q3220072">Lazzaro Baldi</ref>. Monumento funebre al <ref type="person">cardinale <ref type="persName" target="https://www.wikidata.org/wiki/Q304825">Angelo Mai</ref></ref>, scolpito nel <date when="1857" type="construction">1857</date> da <ref type="persName" target="https://www.wikidata.org/wiki/Q434452">Giovanni Battista Benzoni</ref>. L'iscrizione in distici latini che forma l'epitaffio, fu composta dallo stesso <ref type="person">cardinale</ref>. - 3. (Nell'abside) : quadro a olio di <ref type="persName" target="https://www.wikidata.org/wiki/Q114355150">Domenico Ponti</ref>, genovese.</p>

      <p>
        <head>S. BALBINA</head>
        Si ha di questa chiesa antichissima un primo documento nel <ref type="event">sinodo</ref> che <ref type="person">S. <ref type="persName" target="https://www.wikidata.org/wiki/Q42827">Gregorio Magno</ref></ref> indisse nel <date when="594" type="creation">594</date> sotto l'<ref type="person">imperatore <ref type="persName" target="https://www.wikidata.org/wiki/Q181764">Maurizio</ref></ref>; <ref type="event">sinodo</ref> nel quale compariscono i <ref type="person">ri</ref> di essa per la <num type="ordinal" value="1">prima</num> volta. Fu restaurata da <ref type="persName" target="https://www.wikidata.org/wiki/Q132086">Leone <num type="roman" value="3">III</num></ref> (<date when="775" type="renovation">775</date>), da <ref type="persName" target="https://www.wikidata.org/wiki/Q102605">Paolo <num type="roman" value="2">II</num> (Barbo)</ref> nel <date when="1464" type="renovation">1464</date>, da <ref type="persName" target="https://www.wikidata.org/wiki/Q124754">Pio <num type="roman" value="7">VII</num> (Chiaramonti)</ref> nel <date when="1813" type="renovation">1813</date> e finalmente dal <ref type="person">pontefice <ref type="persName" target="https://www.wikidata.org/wiki/Q43727">Leone <num type="roman" value="12">XII</num> (Della Genga)</ref></ref> nel <date when="1825" type="renovation">1825</date>.
      </p>
      <p>Interno. — E' a <num type="cardinal" value="1">una</num> sola navata, con le pareti nude e imbiancate a calce. Sull'altare di destra, bassorilievo di <ref type="person"><ref type="persName" target="https://www.wikidata.org/wiki/Q477441">Mino da Fiesole</ref></ref> e di <ref type="person"><ref type="persName" target="https://www.wikidata.org/wiki/Q668864">Giovanni Dalmata</ref></ref> che faceva parte del monumento di <title><ref type="persName" target="https://www.wikidata.org/wiki/Q102605">Paolo <num type="roman" value="2">II</num></ref></title> nei <ref type="place">sotterranei vaticani</ref> e che fu quivi trasportato nel <date when="1650" type="historical">1650</date>. L'abside fu dipinta per ordine di <ref type="persName" target="https://www.wikidata.org/wiki/Q83159">Clemente <num type="roman" value="7">VII</num></ref> (<date when="1523" type="historical">1523</date>, Medici) dal <ref type="person">fiorentino <ref type="persName" target="https://www.wikidata.org/wiki/Q3615087">Anastasio Fontebono</ref></ref>. La sedia episcopale è lavoro cosmatesco del secolo <date when="XIII" type="construction"><num type="roman" value="13">XIII</num></date>.</p>
      <p>A sinistra: <title>Monumento funebre</title> di <ref type="persName">Stefano de Surdis</ref>, scolpito nel <date when="1300" type="construction">1300</date> da <ref type="persName" target="https://www.wikidata.org/wiki/Q7000871">Giovanni Cosmati</ref>, figlio del <num type="cardinal" value="2">secondo</num> <ref type="persName">Cosimo</ref> e <ref type="person">autore</ref> dei monumenti di <title>S. Prassede</title>, di <title>S. Maria sopra Minerva</title> e di <title>S. Maria Maggiore</title>. Nel convento attiguo è l'ospizio <title>Margherita</title> per le <ref type="person">orfane</ref>. Per visitare la chiesa, suonare alla porta di destra.</p>

      <p>
        <head>S. EUSEBIO</head>
        In <ref type="placeName">piazza Vittorio Emanuele</ref>. È uno dei più antichi titoli di <ref type="placeName">Roma</ref> e l'<ref type="persName">Armellini</ref> cita un grafito, da lui scoperto nelle <ref type="place">catacombe</ref> dei <ref type="person">Ss. <ref type="persName">Pietro</ref> e <ref type="persName">Marcellino</ref></ref> sulla <ref type="placeName">via Labicana</ref>, in cui si cita il <ref xml:lang="lat" type="event">dominicum Sancii Eusebii</ref> come già esistente nella <num type="cardinal" value="1">prima</num>  del secolo <date when="IV" type="historical"><num type="roman" value="4">IV</num></date> : ragione per cui si può supporre la <ref type="placeName">chiesa di S. Eusebio</ref> consacrata dal <ref type="person">papa <ref type="persName" target="https://www.wikidata.org/wiki/Q102105">Liberio</ref></ref> (<date from="352" to="57" type="historical">352-57</date>) subito dopo la morte del <ref type="person">titolare</ref>.</p>
      <p>Nel <date when="494" type="historical">494</date> si trova citata nel catalogo di <ref type="persName" target="https://www.wikidata.org/wiki/Q162135">Gelasio</ref>. Nel <date when="750" type="renovation">750</date> il <ref type="person">papa <ref type="persName" target="https://www.wikidata.org/wiki/Q139467">Zaccaria</ref></ref> restaurò il tetto che era rovinato; ed altri restauri vi fecero <ref type="persName" target="https://www.wikidata.org/wiki/Q103292">Adriano <num type="roman" value="1">I</num></ref> (<date from="772" to="95" type="historical">772-95</date>), <ref type="persName" target="https://www.wikidata.org/wiki/Q132086">Leone <num type="roman" value="3">III</num></ref> (<date from="795" to="816" type="historical">795-816</date>) e <ref type="persName" target="https://www.wikidata.org/wiki/Q167052">Gregorio <num type="roman" value="4">IV</num></ref> (<date from="772" to="95" type="historical">827-44</date>). Nel <date when="1230" type="renovation">1230</date> <ref type="persName" target="https://www.wikidata.org/wiki/Q124831">Gregorio <num type="roman" value="9">IX</num> (Conti)</ref> la fece riedificare dalle fondamenta.</p>
      <p>Nel <date when="1711" type="renovation">1711</date> fu riedificata in parte e <ref type="persName" target="https://www.wikidata.org/wiki/Q3766447">Stefano Fontana</ref> vi aggiunse la facciata. Finalmente nel <date when="1750" type="renovation">1750</date> fu ridotta allo stato in cui si trova attualmente con architettura di <ref type="persName">Nicolò Picconi</ref>.
      </p>
      <p><ref xml:lang="lat" type="text">Heu jacet heic passer mage flavus canaris auro Caelebs quinque fere functus olympiadcs.Majores iste bonis aevium cantunque fefellil Èt domino ac dominae delirium omne fuit. Quorum blandilìis huiusque assueta camcenis Nunc silet et lacrymal squallida in urbe domus. Milla nascendo quae his videi regna renasci Saltem utinam durent ne mea cuncla cadant</ref>.</p>
      <p>(<date when="1834" type="historical">1834</date>),(« Ahi qui giace un canario più biondo dell'oro, morto celibe a <num type="ordinal" value="20">venti</num> anni e che fu la delizia dei suoi <ref type="person">padroni</ref>. La casa dei quali, abituata alle sue consuete canzoni, giace ora squallida nella <ref type="place">città</ref>. Più mite sorte gli era riserbata fin dalla nascita, e avesse voluto il cielo che egli durasse finché io fossi durata »).
      </p>
      <p>Interno. — Nella volta: <title>La gloria di S. Eusebio</title> di <ref type="persName" target="https://www.wikidata.org/wiki/Q76718">Raffaele Mengs</ref>. A destra: <title>S. Celestino</title> del <ref type="persName" target="https://www.wikidata.org/wiki/Q18507966">Ruthard</ref>. Altare maggiore: fu edificato su disegno di <ref type="persName" target="https://www.wikidata.org/wiki/Q2024585">Martino Longhi</ref>; il quadro rappresenta la <title>Madonna fra i <ref type="person">santi</ref></title> di <ref type="persName" target="https://www.wikidata.org/wiki/Q4850375">Baldassarre Croce</ref>. Dietro l'altare vi è un coro di noce scolpito a figure ed ornati; opera del secolo <date when="XVI" type="construction"><num type="roman" value="16">XVI</num></date>.Il quadro del crocifìsso, quivi esistente è di <ref type="persName" target="https://www.wikidata.org/wiki/Q18508013">Cesare Rossetti</ref>. A sinistra: <title>S. Benedetto</title> del medesimo <ref type="persName" target="https://www.wikidata.org/wiki/Q18508013">Rossetti</ref>.</p>
    </body>
  </text>

 <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>Le Chiese di Roma</title>
        <author>A.D. Tani</author>
      </titleStmt>
      <publicationStmt>
        <publisher>Edizioni d'Arte E. Celanza</publisher>
        <date>1912</date>
      </publicationStmt>
      <sourceDesc>
        <p>Testo tratto da documenti storici non strutturati, rielaborato in formato XML secondo le linee guida TEI.</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>

  <text>
    <body>
      <p>
        <head>S. ANASTASIA</head>
        Nella <ref type="place">piazza</ref> omonima ai piedi del <ref type="placeName">Palatino</ref>.</p>
      <p><title>Titolo presbiterale cardinalizio già <ref xml:lang="lat" type="text">SUB PALATIO</ref> ora <ref xml:lang="lat" type="text">S. ANASTASIAE</ref>.</title></p>
      <p>Esisteva originariamente nel <date when="IV" type="construction"><num type="roman" value="4">IV secolo</num></date> al tempo di <ref type="person">papa <ref type="persName" target="https://www.wikidata.org/wiki/Q130997"> Damaso</ref></ref>, ed il <ref type="person">prefetto <ref type="persName" target="https://www.wikidata.org/wiki/Q3842165">Longiniano</ref></ref> vi aveva eretto il <ref type="place">battisterio</ref>. Il suo <num type="ordinal" value="1">primo</num> nome era con tutta probabilità <ref xml:lang="lat" type="text"><ref type="placeName">Anastasis</ref></ref>, cioè Resurrezione, o <ref type="place">Santuario</ref> del risorto Nazzareno. Sorge sulle rovine di costruzioni accessorie del <ref type="placeName">Circo Massimo</ref> e sotto alla <ref type="place">chiesa</ref> sono ampi vani che comunicano col <ref type="placeName">Palatino</ref>, avanzi di muri in <ref xml:lang="lat" type="text">opus quadratum</ref>, e di una <ref type="place">strada</ref> che andava verso il <ref type="placeName">Circo</ref>, e più sotto traccie di una <ref type="place">necropoli</ref> antica. Allorché sul <ref type="placeName">Palatino</ref> vivevano i <ref type="person">rappresentanti dell’imperatore di <ref type="placeName">Bisanzio</ref></ref>; l’<ref type="person">esarca</ref>, quindi il <ref type="person">duca</ref>, ecc., ed ai piedi del <ref type="place">colle romuleo</ref>, verso il <ref type="placeName">Tevere</ref> fioriva il <ref type="place">quartiere greco-bizantino</ref>, questa <ref type="place">chiesa</ref> divenne quasi la <ref type="place">metropolitana</ref> di quegli orientali, e gli <ref type="person">ufficiali di palazzo</ref> la scelsero per luogo di loro <ref type="place">sepoltura</ref>.</p>
      <p>Nell’<date from="VIII" to="IX" type="historical"><num type="roman" value="8">VIII</num> e nel <num type="roman" value="9">IX</num> secolo</date>, le croci processionali delle <num type="ordinal" value="7">sette</num> regioni ecclesiastiche onde <ref type="placeName">Roma</ref> era divisa si conservavano in questa <ref type="place">chiesa</ref>. Da età molto remota fino a verso il <date when="1300" type="historical">1300</date> nella notte di <ref type="event">Natale</ref> il <ref type="person" target="https://www.wikidata.org/wiki/Q134646">Pontefice</ref> giungeva qui all’alba in processione, proveniente da S. Maria Maggiore dove aveva celebrato la messa della mezzanotte, e celebrava la <num type="cardinal" value="2">seconda</num> messa. In questa era particolarmente commemorato il martirio di <ref type="persName" target="https://www.wikidata.org/wiki/Q3615079">Anastasia</ref>, <ref type="person">santa</ref> cara ai <ref type="person">romani</ref>, che la leggenda dice esser <ref type="person">figlia</ref> di un S. Crisogono; ella tornata dall’esilio dell’<ref type="place">isola <ref type="placeName">Palmaria</ref></ref> moriva a Roma, martire, sul rogo, nel <date when="304" type="historical">304</date>. Fino all’epoca dell’<ref type="event">esilio di <ref type="placeName">Avignone</ref></ref> i <ref type="person">papi</ref> venivano qui il mercoledì delle Ceneri e dopo averne distribuite, seguiti dai <ref type="person">cardinali</ref>, dal <ref type="person">clero</ref> e dal <ref type="person">popolo</ref> si recavano a piedi scalzi a <ref type="placeName" target="https://www.wikidata.org/wiki/Q592244">S. Sabina</ref> per aprire la serie delle stazioni quaresimali.</p>
      <p><ref type="persName" target="https://www.wikidata.org/wiki/Q128076">Innocenzo <num type="roman" value="3">III</num></ref> nel <date when="1210" type="renovation">1210</date>, <ref type="persName" target="https://www.wikidata.org/wiki/Q163514">Sisto <num type="roman" value="4">IV</num></ref> nel <date when="1475" type="renovation">1475</date> furono i <num type="cardinal" value="1">primi</num> <ref type="person">restauratori</ref> di questo <ref type="place">edificio</ref>. La <num type="cardinal" value="1">prima</num> ricostruzione moderna che fece sparire il carattere antichissimo di essa si deve ad <ref type="persName" target="https://www.wikidata.org/wiki/Q131579">Urbano VIII</ref>, Barberini, il quale dopo un <ref type="event">turbine</ref> che la minò nel <date when="1636" type="renovation">1636</date> rifece la facciata ed <num type="ordinal" value="1">uno</num> dei campanili coi disegni dell’<ref type="persName" target="https://www.wikidata.org/wiki/Q87128958">Arrigucci</ref>. Poi nel <date when="1722" type="renovation">1722</date> il <ref type="person">cardinale titolare <ref type="persName" target="https://www.wikidata.org/wiki/Q3346439">Antonio Nunez de Attayde da Cunha</ref></ref>, portoghese, continuò i lavori e le diede l’aspetto che ha oggi. Il <ref type="person">cardinale <ref type="persName" target="https://www.wikidata.org/wiki/Q304825">Angelo Mai</ref></ref>, nel <date when="1817" type="renovation">1817</date> e più tardi <ref type="persName" target="https://www.wikidata.org/wiki/Q43720">Pio <num type="roman" value="9">IX</num></ref>, Mastai, completarono i lavori. Nel campanile di destra, dell’<ref type="persName" target="https://www.wikidata.org/wiki/Q87128958">Arrigucci</ref>, sono <num type="ordinal" value="2">due</num> campane, una del <date when="1620" type="historical">1620</date>, l’altra del <date when="1699" type="historical">1699</date>.
      </p>
      <p>STAZIONI. Il giorno di <ref type="event">Natale</ref>, alla <num type="cardinal" value="2">seconda</num> messa dell’aurora. Martedì della <num type="cardinal" value="1">prima</num> settimana di Quaresima. Martedì di Pentecoste. Un piccolo atrio con arco sostenuto da due colonne di porta santa precede il corpo della <ref type="place">chiesa</ref>.</p>
      <p>INTERNO a <num type="ordinal" value="3">tre</num> navate, con <num type="ordinal" value="6">sei</num> colonne per lato (fra cui 7 di pavonazzetto rosso grandioso, 2 di Chio, 2 di granito), sono addossate ai pilastri. Il piano è a croce latina, e solo le <num type="ordinal" value="2">due</num> cappelle ai lati dell’abside ricordano la più antica basilica. <num type="ordinal" value="1">Una</num> iscrizione su lastra marmorea menziona il lavoro generale di restauro compiuto dal <ref type="person">cardinale da <ref type="persName" target="https://www.wikidata.org/wiki/Q3346439">Cunha</ref></ref>. Il soffitto della navata centrale, fatto nel <date when="1722" type="construction">1722</date>, fu restaurato da <ref type="persName" target="https://www.wikidata.org/wiki/Q124754">Pio <num type="cardinal" value="7">VII</num></ref> e da <ref type="persName" target="https://www.wikidata.org/wiki/Q43720">Pio <num type="cardinal" value="10">IX</num></ref>: il <ref type="persName" target="https://www.wikidata.org/wiki/Q3856437">Cerruti</ref> vi dipinse la <title>Gloria di S. Anastasia</title>. Sulle pareti laterali sono quadri ad olio che rappresentano : a destra santi ed a sinistra sante, di nazionalità portoghese.</p>
      <p>NAVATA DI DESTRA. <num type="cardinal" value="1">Prima</num> Cappella, fra <num type="ordinal" value="2">due</num> colonne di porta santa: <title>S. Giovanni Battista</title>, del <ref type="persName" target="https://www.wikidata.org/wiki/Q1192715">Mola</ref>. Quindi è un frammento di antico affresco di <num type="ordinal" value="1">una</num> delle stazioni del Calvario. Sull’ altare della crocera : <title>S. Torribio</title>, canonizzato nel <date when="1726" type="historical">1726</date>, del <ref type="persName" target="https://www.wikidata.org/wiki/Q963875">Trevisani</ref>. Nella Cappella a destra dell’abside è l’Altare delle reliquie; il <ref type="persName" target="https://www.wikidata.org/wiki/Q3220072">Baldi</ref> dipinse le <num type="ordinal" value="4">quattro</num> tele ai lati con episodi della vita di <title>S.Filippo Neri</title> a destra, e di <title>S. Carlo Borromeo</title> di-rimpetto.</p>
      <p>Nel soffitto del presbiterio sono rappresentati l'<title>Agnello Divino</title> ed i <num type="ordinal" value="4">quattro</num> <ref type="person">evangelisti</ref>. Sotto l’altar maggiore, isolato, è la statua marmorea del <ref type="persName">Ferrata</ref>, rappresentante S. Anastasia, le cui reliquie, insieme a quelle di S. Fausta sono conservate nella Confessione.</p>
      <p>Nella conca dell'abside il quadro e gli affreschi sono di <ref type="persName" target="https://www.wikidata.org/wiki/Q3220072">Lazzaro Baldi</ref> che in essi rappresentò <title>S. Anastasia</title>, e nel quadro dell’altare, la <title>Natività</title>. Le <num type="ordinal" value="2">due</num> tombe di <ref type="persName">Paolo Febi</ref>, <date when="1649" type="construction">1649</date>, e di <ref type="persName">Francesco Febi</ref>, <date when="1680" type="construction">1680</date>, sono di <ref type="persName">T. Ripoli</ref>. Il <ref type="person">cardinale <ref type="persName" target="https://www.wikidata.org/wiki/Q3105117">Costaguti</ref></ref> nel <date when="1793" type="renovation">1793</date> completò i restauri di questa parte della <ref type="place">chiesa</ref>.</p>
      <p>La Cappella a sinistra dell’abside è dedicata a S. Girolamo e la sua imagine si vede sull’altare che è dotato di <num type="ordinal" value="4">quattro</num> colonnine, a baldacchino di lumachella lenticolare persichina gialla, proviene dall’antico S. Pietro e venne portato qui dal <ref type="person">cardinale <ref type="persName">Febi</ref></ref>. Vi si conservano preziose reliquie, fra cui <num type="cardinal" value="1">un</num> calice di smalto che si crede abbia appartenuto a S. Girolamo. Nella crocera è sull’altare la <title>Vergine del Rosario</title>, di <ref type="persName" target="https://www.wikidata.org/wiki/Q3220072">Lazzaro Baldi</ref>, fra <num type="ordinal" value="2">due</num> colonne di alabastro giallo fiorito a rosé, dislocato. Indi è la tomba dell’erudito <ref type="person">cardinale <ref type="persName" target="https://www.wikidata.org/wiki/Q304825">Angelo Mai</ref></ref>, <date when="1854" type="construction">1854</date>, con <num type="ordinal" value="1">una</num> iscrizione in elegante latino dettata dal <ref type="person">cardinale</ref> stesso. Il monumento è opera del <ref type="persName">Bezzoni</ref>.</p>
      <p>Nella Cappella della NAVATA DI SINISTRA: Santi Giorgio e Publio, di <ref type="persName" target="https://www.wikidata.org/wiki/Q3592316">Stefano Parocel</ref>.</p>
      <p><ref type="person">CARDINALI TITOLARI</ref>. — Fra i <ref type="person">cardinali titolari</ref> più noti, oltre quelli nominati, si contano: <ref type="persName" target="https://www.wikidata.org/wiki/Q125984">Anastasio</ref>, <date when="499" type="historical">499</date> — <ref type="persName">Tomacelli</ref>, che divenne <ref type="persName" target="https://www.wikidata.org/wiki/Q165561">Bonifacio <num type="roman" value="9">IX</num></ref>, <date when="1389" type="historical">1389</date> — <ref type="persName">Lorenzo Campeggio</ref>, <date from="1518" to="1528" type="historical">1518-1528</date> — <ref type="persName">A. C. Ferrari</ref>, <date from="1894" to="1921" type="historical">1894-1921</date>.</p>
      <p><ref type="persName">Crescimbeni</ref> : <title><ref xml:lang="lat" type="title">Historia</ref> della Basilica di S. Anastasia.</title> <ref type="place">Roma</ref> <date when="1722" type="historical">1722</date>.</p>

      <p>
        <head>S. BALBINA</head> 
        Sull'<ref type="placeName">Aventino</ref>, presso le <ref type="placeName">Terme Antoniniane</ref>.</p>
      <p><title>Titolo presbiterale <ref xml:lang="lat" type="text">S. BALBINAE</ref> Dipende dal Capitolo di S. Pietro.</title></p>
      <p>Il <ref type="person">pontefice <ref type="persName" target="https://www.wikidata.org/wiki/Q132797">S. Marco</ref></ref>, nel <date when="366" type="construction">366</date>, oltre alla <ref type="placeName">basilica di S. Marco</ref>, in <ref type="place">città</ref>, eresse una <ref type="place">basilica</ref> dedicata al Salvatore sulla <ref type="placeName">via Ardeatina</ref>, che passa qui presso, nella regione delle <ref type="placeName">catacombe di Balbina</ref>, che si ritiene siano unite a quelle di <ref type="placeName">Callisto</ref>. Se questa nostra <ref type="place">chiesa</ref> non è stata edificata da S. Marco è pur tuttavia antichissima, di età costantiniana, ed <num type="ordinal" value="1">uno</num> dei pochi esempi di <ref type="place">edificio</ref> pagano trasformato in cristiano e l’unico poi che non sia stato trasformato con l’aggiunta di colonne. E’ una sala della casa di <ref type="persName" target="https://www.wikidata.org/wiki/Q1231642">L. Fabio Cilone</ref>, console nel <date when="204" type="historical">204</date>, convertita in <ref type="place">chiesa</ref> e poggia sopra avanzi di mura serviane.</p>
      <p>Al tempo di <ref type="persName" target="https://www.wikidata.org/wiki/Q42827">S. Gregorio Magno</ref>, nel <date when="600" type="historical">600</date>, allorché essa è nominata, a proposito di un <ref type="event">sinodo</ref> che quel pontefice vi tenne, era già dedicata a <ref type="persName" target="https://www.wikidata.org/wiki/Q508782">Santa Balbina</ref>, martire, durante la <ref type="event">persecuzione di <ref type="persName" target="https://www.wikidata.org/wiki/Q714856">Trajano</ref></ref>. <ref type="persName" target="https://www.wikidata.org/wiki/Q1643096">Marco Barbo</ref>, nipote di <ref type="persName" target="https://www.wikidata.org/wiki/Q102605">Paolo <num type="roman" value="2">II</num></ref> la ridusse quale è ora nel <date when="1474" type="renovation">1474</date>, alterando il tipo lasciato dai restauri di <ref type="persName" target="https://www.wikidata.org/wiki/Q132086">Leone <num type="roman" value="3">III</num></ref>. Poi il <ref type="person">cardinale titolare <ref type="persName" target="https://www.wikidata.org/wiki/Q3396079">Arrigoni</ref></ref> nel <date when="1600" type="renovation">1600</date> vi fece alcune modificazioni e la decorò con affreschi. Altri restauri vi furono eseguiti nel <date when="1813" type="renovation">1813</date>, <date when="1825" type="renovation">1825</date>, <date when="1884" type="renovation">1884</date>.
      </p>
      <p>FESTE: <ref type="event"><num type="ordinal" value="31">31</num> marzo</ref>, S. Balbina.</p>
      <p>STAZIONE. Il martedì dopo la seconda domenica di <ref type="event">Quaresima</ref>.</p>
      <p>IL PORTICO ad archi è anteriore all’<date notBefore="XI" notAfter="XIX"><num type="roman" value="11">XI secolo</num></date>.</p>
      <p>L’INTERNO, già sala della <ref type="place">casa di <ref type="persName" target="https://www.wikidata.org/wiki/Q1231642">Cilone</ref></ref>, <num type="lenght" quantity="23" unit="mt"> lungo metri 23</num>, <num type="width" quantity="16" unit="mt">largo 16</num>, è semplice e e ad una sola navata.</p>
      <p>Sull’ altare a destra è un bel bassorilievo della <title>Crocefissione di Cristo</title>, con le figure della Vergine e S. Giovanni ai lati : fu tolto da un altare di S. Marco, che <ref type="persName" target="https://www.wikidata.org/wiki/Q102605">Paolo <num type="roman" value="2">II</num></ref> aveva costruito, coi disegni di <ref type="persName" target="https://www.wikidata.org/wiki/Q3894324">Paolo il Dalmata</ref> nell’antico S. Pietro e portato qui, dalle <ref type="placeName">Grotte Vaticane</ref> nel <date when="1650" type="historical">1650</date>. Sotto l’altar maggiore in una urna di alabastro fiorito sono le reliquie di S. Balbina e di suo <ref type="person">padre</ref>, S. Quirino, martire, che era stato tribuno. Nell’abside <ref type="persName" target="https://www.wikidata.org/wiki/Q3615087">Anastasio Fontebuono, fiorentino</ref>, verso il <date when="1600" type="construction">1600</date> affrescò la <title>Gloria dei Ss. Quirinio e Balbina</title>.</p>
      <p>Sotto è una bella sedia episcopale, di lavoro cosmatesco del <date when="XIII" type="construction"><num type="roman" value="13">XIII</num></date> secolo. Sull’altare di sinistra è : a lato di esso la bellissima e ricca tomba, piena di mosaici, del <ref type="person">cardinale <ref type="persName">Stefano dei Surdi</ref></ref>, <date when="1295" type="historical">1295</date>, <ref type="person">cappellano</ref> di <ref type="persName" target="https://www.wikidata.org/wiki/Q134646">Bonifacio <num type="roman" value="8">VIII</num></ref>. <ref type="persName" target="https://www.wikidata.org/wiki/Q7000871">Giovanni di Cosma</ref> ne è <ref type="person">autore</ref>, ed un tempo si trovava nell’antico S. Pietro.
      </p>
      <p>IL <ref type="place">MONASTERO</ref> nel medio evo era fortificato, e ne mostra ancora traccio, fu costruito sui muri di opera reticolata regolare della <ref type="place">casa di <ref type="persName" target="https://www.wikidata.org/wiki/Q1231642">Cilone</ref></ref>, è attraverso le mura Serviane, di cui si vedono avanzi nel <ref type="place">refettorio</ref> e nel <ref type="place">giardino</ref>. Fu abitato da <ref type="person">monaci greci</ref>, ed al tempo di <ref type="persName" target="https://www.wikidata.org/wiki/Q163514">Sisto <num type="roman" value="4">IV</num></ref>, come scrive il <ref type="persName" target="https://www.wikidata.org/wiki/Q2403504">Volterrano</ref>, il <ref type="person">priore</ref> era colui che nella <ref type="place">cappella papale</ref> della messa della Resurrezione leggeva, come si costuma tuttora, il Vangelo in greco. <ref type="persName" target="https://www.wikidata.org/wiki/Q44281">S. Ignazio di Loyola</ref> comperò un giorno una grande vigna, presso le <ref type="placeName">terme Antoniniane</ref>, che era di proprietà della <ref type="placeName">chiesa di S. Balbina</ref>, e qui fece la <ref type="place">residenza d’estate</ref> degli <ref type="person">allievi del <ref type="place">collegio</ref> germanico</ref> e dei <ref type="person">novizi dell’<ref type="organization">ordine dei Gesuiti</ref></ref>. Quando nel luglio <date when="1556" type="historical"><num type="ordinal" value="1556">1556</num></date> il <ref type="person">duca <ref type="persName" target="https://www.wikidata.org/wiki/Q80847">d’Alba</ref></ref> minacciava <ref type="placeName">Roma</ref>, il <ref type="person">santo</ref>, che abitava qui, per timore si recò subito a <ref type="placeName">Roma</ref>. Poco dopo <ref type="person">egli</ref> moriva. Le <ref type="person">suore agostiniane</ref> vi hanno abitato per qualche tempo, e <date notBefore="1500" notAfter="1912" type="historical">pochi anni fa</date> vi tenevano un <ref type="place">rifugio</ref> per <ref type="person">peccatrici pentite</ref>, ed ora vi è un <ref type="place">ospizio per <ref type="person">vecchi ed orfani</ref></ref>.</p>
      <p><ref type="person">Cardinali titolari</ref> più noti. — <ref type="persName" target="https://www.wikidata.org/wiki/Q284092">John Kemp</ref>, <date from="1440" to="1445" type="historical">1440-1445</date> — <ref type="persName" target="https://www.wikidata.org/wiki/Q1386991">G. B, Cybo</ref>, <date from="1473" to="1477" type="historical">1473-1477</date>, più tardi <ref type="persName" target="https://www.wikidata.org/wiki/Q161351">Innocenzo <num type="roman" value="8">VIII</num></ref> — <ref type="persName" target="https://www.wikidata.org/wiki/Q682478">Giacomo Sadoleto</ref>, <date when="1545" type="historical">1545</date> — <ref type="persName" target="https://www.wikidata.org/wiki/Q3396079">Pompeo Arrigoni</ref>, <date from="1597" to="1616" type="historical">1597-1616</date> — <ref type="persName" target="https://www.wikidata.org/wiki/Q766035">Auguste René Dubourg</ref>, <date when="1916" type="historical">1916</date>.</p>

      <p>  
        <head>S. EUSEBIO</head>
        Piazza Vittorio Emanuele.</p>
      <p>Titolo presbiterale <title><ref xml:lang="lat" type="text">S. EUSEBII</ref> Parrocchia.</title></p>
      <p><ref type="person"><ref type="persName" target="https://www.wikidata.org/wiki/Q3820734">Eusebio</ref>, patrizio romano, prete</ref>, fu condannato nel <date when="357" type="historical">357</date>, a morire di fame, perchè confessore del simbolo della fede, di <ref type="persName" target="https://www.wikidata.org/wiki/Q44024">Atanasio</ref>, a tempo di <ref type="persName" target="https://www.wikidata.org/wiki/Q450702">Costanzo</ref> — ariano — <ref type="person">figlio di <ref type="persName" target="https://www.wikidata.org/wiki/Q8413">Costantino</ref></ref> e si estinse per questa condanna nella sua <ref type="place">dimora sull’<ref type="placeName">Esquilino</ref></ref>. La <ref type="place">casa</ref> si trovava tra i <ref type="place">giardini di <ref type="persName" target="https://www.wikidata.org/wiki/Q666605">Elio Lamia</ref> e quelli di <ref type="persName">Calyclano</ref> e di <ref type="persName" target="https://www.wikidata.org/wiki/Q2331658">Statilio Tauro</ref></ref>, creati nei primi tempi dell'Impero, quando questa parte della <ref type="place">città</ref> era compresa nella <num type="cardinal" value="5">quinta</num> regione augustea. Presso la <ref type="place">casa di <ref type="persName">Eusebio</ref></ref> era il <ref xml:lang="lat" type="place">Castellum dell' Aqua Julia</ref>, costruito da <ref type="persName" target="https://www.wikidata.org/wiki/Q1442">Severo</ref> di cui vediamo ancora grandi avanzi nel <ref type="place">giardino di <ref type="placeName">Piazza Vittorio Emanuele</ref></ref> vicino al <ref xml:lang="lat" type="place">Castellum</ref> sono stati trovati i cosidetti trofei di <ref type="persName" target="https://www.wikidata.org/wiki/Q177975">Mario</ref> per la sua vittoria sui <ref type="person">Cimbri</ref>, che <ref type="persName" target="https://www.wikidata.org/wiki/Q133350">Sisto <num type="" value="5">V</num></ref> fece portare sul <ref type="placeName">Campidoglio</ref>. Erano essi tanto celebrati che nel <date when="XIV" type="historical"><num type="XIV" value="14">XIV</num> secolo</date>, questa parte di <ref type="placeName">Roma</ref> tutta coperta di orti e di vigne, fu detta <ref type="placeName">Cimbriana</ref>, ed una <ref type="place">piazzetta</ref> dinanzi alla <ref type="place">chiesa</ref>, <ref type="placeName">piazza del Cimbro</ref>.</p>
      <p>Sembra che i ruderi della magnifica <ref type="place">villa di <ref type="persName" target="https://www.wikidata.org/wiki/Q666605">Elio Lamia</ref></ref> abbiano dato origine alla leggenda popolare che quassù fosse un meraviglioso <ref type="placeName">palazzo</ref> con <num type="ordinal" value="200">duecento</num> colonne eretto da <ref type="persName" target="https://www.wikidata.org/wiki/Q1782">Gordiano</ref>, e che la <ref type="placeName">chiesa di S. Eusebio</ref> sorgesse sulle rovine del <ref type="place">palazzo imperiale</ref>. Verso la metà del <date when="IV" type="construction"><num type="roman" value="4">IV</num> secolo</date> nella <ref type="place">casa di <ref type="persName">Eusebio</ref></ref> si era aperto un <ref type="place">oratorio</ref> e in una iscrizione graffita troviamo nominato un <ref xml:lang="lat" type="text">Olympus, lector de dominico Eusebii</ref>. Più tardi nei <ref type="event">concili di <ref type="persName" target="https://www.wikidata.org/wiki/Q162135">Gelasio</ref>, <date when="494" type="historical">494</date>, e di <ref type="persName" target="https://www.wikidata.org/wiki/Q160935">Simmaco</ref>, <date when="499" type="historical">499</date></ref>, appare il nome di un <ref xml:lang="lat" type="text">Valentinus, archipresbyler</ref> del titolo di <ref type="persName">Eusebio</ref>. Il <ref type="person">pontefice <ref type="persName" target="https://www.wikidata.org/wiki/Q139467">Zaccaria</ref></ref> restaurò l’oratorio nel <date when="750" type="renovation">750</date>, ed <ref type="persName" target="https://www.wikidata.org/wiki/Q103292">Adriano <num type="lat" value="1">I</num></ref>, <date from="772" to="795" type="renovation">772-795</date> lo fece ricostruire. Ingrandito, più tardi divenne chiesa che nel <date when="1238" type="renovation">1238</date> fu tutta restaurata. Vi si posero allora <num type="ordinal" value="3">tre</num> altari e fu dedicata e consacrata ai santi martiri <ref type="persName" target="https://www.wikidata.org/wiki/Q3820734">Eusebio</ref> e <ref type="persName">Vincenzo</ref>, come è narrato nell’iscrizione di <ref type="persName" target="https://www.wikidata.org/wiki/Q124831">Gregorio <num type="roman" value="9">IX</num>, Conti</ref>, a lato della porta d’ingresso.</p>
      <p>Sembra che <ref type="persName" target="https://www.wikidata.org/wiki/Q103625">Niccolò <num type="roman" value="4">IV</num></ref>, nel <date when="1288" type="historical">1288</date> abbia dato la <ref type="place">chiesa</ref> a <ref type="persName" target="https://www.wikidata.org/wiki/Q118081">Pietro da Morrone</ref>, fondatore dei <ref type="organization">Celestini</ref>, dei quali però troviamo menzione soltanto quando nel <date when="1573" type="historical">1573</date> essi presero possesso del <ref type="place">palazzo del <ref type="person">cardinale titolare</ref></ref>, che era a sinistra della <ref type="place">chiesa</ref>, dato loro da <ref type="persName" target="https://www.wikidata.org/wiki/Q83029">Gregorio <num type="roman" value="13">XIII</num>, Boncompagni</ref>. Questi <ref type="person">frati</ref> vi rimasero fino ai giorni di <ref type="persName" target="https://www.wikidata.org/wiki/Q43727">Leone <num type="roman" value="12">XII</num>, della Genga</ref>, <date from="1823" to="1829" type="historical">1823-1829</date>, il quale soppresse l’<ref type="organization">ordine</ref>. Un <num type="cardinal" value="1">primo</num> restauro in tempi recenti fu eseguito nel <date when="1711" type="renovation">1711</date>; nel <date when="1750" type="renovation">1750</date> per la generosità del <ref type="person">cardinale <ref type="persName" target="https://www.wikidata.org/wiki/Q3054630">Enrico <ref xml:lang="es" type="persName">Enriquez</ref></ref></ref> la <ref type="placeName">chiesa</ref> fu tutta risarcita e trasformata, coi disegni di <ref type="persName">Nicola Picconi</ref> e prese l’aspetto che ha oggi. Nulla rimane della <ref type="place">chiesa</ref> più antica eccetto il campanile.</p>
      <p><ref type="persName" target="https://www.wikidata.org/wiki/Q43727">Leone <num type="roman" value="12">XII</num></ref> l’affidò ai <ref type="organization">PP. Gesuiti</ref>, che vi aprirono una casa per gli esercizi spirituali, grandemente frequentati da ogni classe di <ref type="person">gente</ref> fra gli altri si ricorda <ref type="persName"><ref xml:lang="fr" type="persName" target="https://www.wikidata.org/wiki/Q605534">M.Lacordaire</ref></ref>, che più tardi divenuto <ref type="person">frate domenicano</ref> fu una illustrazione del suo ordine. I <ref type="organization">Gesuiti</ref> vi rimasero fino al <date when="1873" type="historical">1873</date>, quando il <ref type="place">monastero</ref> fu soppresso e divenne proprietà del <ref type="organization">Governo italiano</ref>, che più tardi vi pose una <ref type="place">scuola d’igiene</ref>. <ref type="persName" target="https://www.wikidata.org/wiki/Q43734">Gregorio <num type="roman" value="12">XVI</num></ref>, nel <date when="1839">1839</date> trasferì il vetusto titolo di questa <ref type="place">chiesa</ref> a <ref type="placeName">S. Gregorio sul Celio</ref>, ma <ref type="persName" target="https://www.wikidata.org/wiki/Q43720">Pio <num type="roman" value="9">IX</num></ref>, nel <date when="1877" type="hisotrical">1877</date> lo ristabilì. Contemporaneamente all’apertura della prima tipografia in <ref type="placeName">Roma</ref>, in <ref xml:lang="lat" type="place">domo magnifici viri <ref type="persName">Petri de Maximo</ref></ref>, se ne aprì un’altra nel <ref type="placeName">monastero di S. Eusebio</ref> e la <num type="cardinal" value="1">prima</num> opera che uscì da qui, nel <date when="1470" type="historical">1470</date>, fu quella dal titolo : <title><ref xml:lang="lat" type="title">Omiliae beati Johannis Chrysostami</ref></title>, tradotto dal greco da <ref type="persName" target="https://www.wikidata.org/wiki/Q2266954">Francesco Aretino</ref>.</p>
      <p>Quando nel <date when="1870" type="historical">1870</date> fu chiusa la <ref type="placeName">chiesa di S. Antonio</ref>, presso <ref>S. Maria Maggiore</ref>, venne trasferita a <ref type="placeName">S. Eusebio</ref> l’antica usanza della <ref type="event">pubblica benedizione dei <ref type="animal">cavalli, muli ed asini</ref></ref>, che si fa tuttora il <ref type="event"><num type="ordinal" value="17">17</num> gennaio</ref> di ogni anno. Nel <date when="1890" type="renovation">1890</date> dopo un sommario restauro la <ref type="place">chiesa</ref> fu riaperta al culto ed eretta a <ref type="place">parrocchia</ref>.</p>
      <p><ref type="event">FESTA TITOLARE: <num type="ordinal" value="14">14 agosto</num></ref>. In questo giorno vi si celebra anche la <ref type="event">festa di S. Orosio</ref>, <ref type="person">prete spagnolo</ref> che fu martirizzato nella <ref type="place">casa stessa di S. Eusebio</ref>, e nello stesso tempo.</p>
      <p><ref type="place">STAZIONE</ref>. Il venerdì dopo la <num type="cardinal" value="4">quarta</num> domenica di <ref type="event">Quaresima</ref>.</p>
      <p>Il CAMPANILE di stile medievale, neo-latino, è del <date when="1220" type="construction">1220</date>; in esso vi sono <num type="ordinal" value="2">tre</num> campane delle seguenti date: <date when="1803" type="construction">1803</date>, <date when="1845" type="construction">1845</date>, <date when="1903" type="construction">1903</date>.</p>
      <p>FACCIATA. Costruita da <ref type="persName" target="https://www.wikidata.org/wiki/Q3766447">Antonio Fontana</ref> nel <date when="1711" type="construction">1711</date>, ha <num type="ordinal" value="2">due</num> rampe che salgono ad <num type="ordinal" value="1">un</num> piccolo portico (trasformazione dell’antico). A destra della porta è l’iscrizione di <ref type="persName" target="https://www.wikidata.org/wiki/Q124831">Gregorio <num type="roman" value="9">IX</num></ref>.</p>
      <p>INTERNO, semplice, a <num type="ordinal" value="3">tre</num> navate, con <num type="ordinal" value="4">quattro</num> altari per lato. Nel soffitto della volta centrale è la pittura di <ref type="persName" target="https://www.wikidata.org/wiki/Q76718">Raffaello Mengs</ref>, <date when="1759" type="construction">1759</date>, con la <title>Gloria di S. Eusebio</title>, che in una figura riprodusse le fattezze di sua <ref type="person">moglie</ref>. Sull’ altare della crocera, a destra, è <title>S. Celestino</title>, di <ref type="persName" target="https://www.wikidata.org/wiki/Q18507966">Ruthard</ref>, fiammingo, <ref type="person">monaco celestino</ref>, fra <num type="ordinal" value="2">due</num> colonne di breccia pavonazza.</p>
      <p>L’ALTAR MAGGIORE, disegnato da <ref type="persName" target="https://www.wikidata.org/wiki/Q2024585">Martino Longhi</ref>, ha <num type="ordinal" value="4">quattro</num> colonne di breccia pavonazza e la pittura della <title>Vergine</title>, coi santi <title>Eusebio e Vincenzo</title>, di <ref type="persName" target="https://www.wikidata.org/wiki/Q4850375">Baldassarre Croce</ref>, che si trovava su di esso, è stato rimosso nella parte posteriore verso il Coro. Sotto l’Altar maggiore si suppone che siano le reliquie dei Ss.<ref type="person" target="https://www.wikidata.org/wiki/Q3820734"> Eusebio</ref>, <ref type="person">Orosio</ref> e <ref type="person">Paolino</ref>.</p>
      <p>Nella tribuna è il bellissimo <title>CORO</title> in noce intagliato, con piccole statue di santi ed arabeschi, del <date when="1556" type="construction">1556</date>; ed il <title>Crocefisso</title> dipinto da <ref type="persName" target="https://www.wikidata.org/wiki/Q18508013">Cesare Rossetti</ref>. Sull’ altare della crocera a sinistra, fra <num type="ordinal" value="2">due</num> colonne di breccia corallina, è S. Benedetto, di <ref type="persName" target="https://www.wikidata.org/wiki/Q18508013">Cesare Rossetti</ref>.</p>
      <p><ref type="person">Cardinali titolari</ref> più noti. — <ref type="persName"><ref xml:lang="lat" type="persName">Valentinus</ref></ref> (?), <date when="492" type="historical">492</date> — <ref type="persName">Probiano</ref>, <date when="494" type="historical">494</date> — <ref type="persName" target="https://www.wikidata.org/wiki/Q117125">Oliviero Carafa</ref>, <date from="1470" to="1476" type="historical">1470-1476</date>, più tardi anche Commendatario della <ref type="place">chiesa</ref> — <ref type="persName" target="https://www.wikidata.org/wiki/Q132711">Camillo Borghese</ref>, <date from="1595" to="1599" type="historical">1595-1599</date>, più tardi papa <ref type="persName" target="https://www.wikidata.org/wiki/Q132711">Paolo <num type="roman" value="5">V</num></ref> — <ref type="persName" target="https://www.wikidata.org/wiki/Q777310">Benedetto Pamphily</ref>, <date from="1630" to="1644" type="historical">1630-1644</date>, più tardi papa <ref type="persName" target="https://www.wikidata.org/wiki/Q101266">Innocenzo <num type="roman" value="10">X</num></ref> — <ref type="persName"><ref xml:lang="es" type="persName" target="https://www.wikidata.org/wiki/Q3054630">Enrico Enriquez</ref></ref>, <date from="1754" to="1756" type="historical">1754-1756</date> — <ref type="persName"><ref xml:lang="fr" type="persName">Jean de la Rochechouart</ref></ref>, <date from="1762" to="1777" type="historical">1762-1777</date> — <ref type="persName"><ref xml:lang="de" type="persName">G. B. Kutskher</ref></ref>, <date from="1877" to="1881" type="historical">1877-1881</date> — <ref type="persName" target="https://www.wikidata.org/wiki/Q712613">Giovanni Csernoch</ref>, <date when="1914" type="historical">1914</date>- . . .</p>
    </body>
  </text>
</TEI>
